package classMetier.Util;

public enum CategorieMedicament {
    ANTALGIQUE,
    ANALGESIQUE,
    ANTIINFLAMATOIRES,
    ANTIVIRAUX,
    ANTISPAMODIQUES,
    CORTICOIDES, ANTIBACTERIENS, POLYMIXINES, TETRECYCLINES, ANTITUBERCULEUX,

}
